company_link = {
    "adobe": "https://www.adobe.com/",
    "adidas": "https://www.adidas.com/",
    "airbnb": "https://www.airbnb.com/",
    "alcampo": "https://www.compraonline.alcampo.es/",
    "alibaba": "https://alibaba.com/",
    "aliexpress": "https://aliexpress.com/",
    "autodesk": "https://www.autodesk.com/",  
    "amazon": "https://www.amazon.com/",
    "american express": "https://www.americanexpress.com/",
    "angellist": "https://www.angellist.com/",
    "apple": "https://www.apple.com/",
    "asana": "https://asana.com/es",
    "atlassian": "https://www.atlassian.com/",
    "att": "https://www.att.com/",
    "axis bank": "https://www.axisbank.com/",
    "baidu": "https://www.baidu.com/",
    "banco sabadell": "https://www.bancsabadell.com/",
    "bbva": "https://www.bbva.es",
    "bbc": "https://www.bbc.com/",
    "best buy": "https://www.bestbuy.com/",
    "binance": "https://www.binance.com/",
    "blackrock": "https://www.blackrock.com/",
    "blender": "https://www.blender.org/",
    "bloomberg": "https://www.bloomberg.com/",
    "boeing": "https://www.boeing.com/",
    "booking": "https://www.booking.com/",
    "buzzfeed": "https://www.buzzfeed.com/",
    "canva": "https://canva.com/",
    "carrefour": "https://carrefour.es/",
    "cash app": "https://cash.app/",
    "chewy": "https://chewy.com/",
    "chime": "https://chime.com/",
    "cine yelmo": "https://yelmocines.es/",  
    "cinesa": "https://www.cinesa.es/",      
    "cisco": "https://cisco.com/",
    "citibank": "https://citi.com/",
    "clickup": "https://clickup.com/",
    "cnn": "https://cnn.com/",
    "coinbase": "https://coinbase.com/",
    "cortefiel": "https://cortefiel.com/",
    "cura": "https://ultimaker.com/",
    "columbia": "https://columbia.com",
    "costco": "https://costco.com/",
    "coursera": "https://coursera.org/",
    "cnbc": "https://www.cnbc.com/",
    "dell": "https://dell.com/",
    "disney": "https://disney.com/",
    "disney plus": "https://disneyplus.com/",
    "doordash": "https://doordash.com/",
    "dropbox": "https://dropbox.com/",
    "el corte inglés": "https://elcorteingles.es/",
    "ebay": "https://ebay.com/",
    "etrade": "https://etrade.com/",
    "etsy": "https://etsy.com/",
    "evernote": "https://evernote.com/",
    "expedia": "https://www.expedia.com/",
    "facebook": "https://facebook.com/",
    "fedex": "https://fedex.com/",
    "fidelity": "https://fidelity.com/",
    "figma": "https://figma.com/",
    "financial times": "https://ft.com/",
    "fiver": "https://fiverr.com/",
    "forbes": "https://forbes.com/",
    "genially": "https://genial.ly/",
    "gemini": "https://gemini.com/",
    "github": "https://github.com/",
    "gmail": "https://www.google.com/intl/es/gmail/about/",
    "godaddy": "https://godaddy.com/",
    "godot": "https://godotengine.org/",
    "godot engine": "https://godotengine.org/",
    "google": "https://www.google.com/",
    "grubhub": "https://grubhub.com/",
    "harvard": "https://harvard.edu/",
    "harvard university": "https://harvard.edu/",
    "hbo": "https://hbo.com/",
    "hbo max": "https://hbomax.com/",
    "hcltech": "https://hcltech.com/",
    "hdfc bank": "https://hdfcbank.com/",
    "huawei": "https://huawei.com/",
    "hubspot": "https://hubspot.com/",
    "hsbc": "https://hsbc.com/",
    "hulu": "https://www.hulu.com/",
    "icici bank": "https://icicibank.com/",
    "ikea": "https://ikea.com/",  
    "instagram": "https://instagram.com/",
    "intel": "https://intel.com/",
    "investopedia": "https://investopedia.com/",
    "johnson and johnson": "https://jnj.com/",
    "kth":"https://www.kth.se/",
    "khan academy": "https://khanacademy.org/",
    "kickstarter": "https://kickstarter.com/",
    "kpmg": "https://kpmg.com/xx/en/home.html",
    "kraken": "https://kraken.com/",
    "lego": "https://lego.com/",
    "lego house": "https://legohouse.com/",
    "linkedin": "https://linkedin.com/",
    "lyft": "https://lyft.com/",
    "lufthansa": "https://lufthansa.com/",
    "marvel": "https://marvel.com/",
    "mailchimp": "https://mailchimp.com/",
    "marriott": "https://marriott.com/",
    "marriott bonvoy": "https://marriott.com/",
    "marketwatch": "https://marketwatch.com/",
    "mastercard": "https://mastercard.com/",
    "medium": "https://medium.com/",
    "mecabricks": "https://mecabricks.com/",
    "meta": "https://meta.com/",
    "microsoft": "https://www.microsoft.com/",
    "monday": "https://monday.com/",
    "morningstar": "https://morningstar.com/",
    "morgan stanley": "https://morganstanley.com/",
    "netflix": "https://netflix.com/",
    "netgear": "https://netgear.com/",
    "the new york times": "https://nytimes.com/",
    "nike": "https://nike.com/",
    "notion": "https://notion.so/",
    "nvidia": "https://nvidia.com/",
    "openbank": "https://openbank.es/",
    "oracle": "https://oracle.com/",
    "outlook": "https://www.microsoft.com/es-es/",
    "panasonic": "https://panasonic.com/",
    "paypal": "https://paypal.com/",
    "pedro del hierro": "https://pedrodelhierro.com/",  
    "pfizer": "https://pfizer.com/",
    "pinterest": "https://pinterest.com/",
    "pocket": "https://getpocket.com/",
    "postmates": "https://postmates.com/",
    "prime video": "https://primevideo.com/",
    "printables": "https://www.printables.com/",
    "protonmail": "https://protonmail.ch/",
    "proton mail": "https://protonmail.ch/",
    "quora": "https://quora.com/",
    "reddit": "https://reddit.com/",
    "reuters": "https://reuters.com/",
    "revolut": "https://revolut.com/",
    "robinhood": "https://robinhood.com/",
    "rolex": "https://rolex.com/",
    "safeway": "https://safeway.com/",
    "samsung": "https://samsung.com/",
    "santander": "https://santander.com.ar/",
    "sdu":"https://www.sdu.dk/da",
    "shell": "https://shell.com/",
    "shopify": "https://shopify.com/",
    "siemens": "https://siemens.com/",
    "skype": "https://skype.com/",
    "slack": "https://slack.com/",
    "snapchat": "https://snapchat.com/",
    "sofi": "https://sofi.com/",
    "sony": "https://sony.com/",
    "sothebys": "https://sothebys.com/",
    "spacex": "https://spacex.com/",
    "spotify": "https://open.spotify.com/",
    "square": "https://squareup.com/",
    "starbucks": "https://starbucks.com/",
    "stripe": "https://stripe.com/",
    "substack": "https://substack.com/",
    "tata": "https://tcs.com/",
    "tata consultancies": "https://tcs.com/",
    "tata consultancy": "https://tcs.com/",
    "tata consultancy services": "https://tcs.com/",
    "target": "https://target.com/",
    "td ameritrade": "https://tdameritrade.com/",
    "tencent": "https://tencent.com/",
    "tesla": "https://tesla.com/",
    "the guardian": "https://theguardian.com/",
    "the north face": "https://thenorthface.com/",
    "the wall street journal": "https://wsj.com/",
    "the washington post": "https://www.washingtonpost.com/",
    "tiktok": "https://tiktok.com/",
    "tinkercad": "https://tinkercad.com/",
    "todoist": "https://todoist.com/",
    "toyota": "https://www.toyota.com/",
    "trello": "https://trello.com/",
    "tumblr": "https://tumblr.com/",
    "twitch": "https://twitch.tv/",
    "twilio": "https://twilio.com/",
    "twitter": "https://twitter.com/",
    "uber": "https://uber.com/",
    "uber eats": "https://ubereats.com/",
    "ultimaker": "https://ultimaker.com/",
    "ultimaker cura": "https://ultimaker.com/",
    "unreal engine": "https://unrealengine.com/",
    "ups": "https://ups.com/",
    "uptimerobot": "https://uptimerobot.com/",
    "vanguard": "https://vanguard.com/",
    "venmo": "https://venmo.com/",
    "verizon": "https://verizon.com/",
    "vimeo": "https://vimeo.com/",
    "visa": "https://visa.com/",
    "wall street journal": "https://wsj.com/",
    "walmart": "https://walmart.com/",
    "washington post": "https://washingtonpost.com/",
    "wechat": "https://wechat.com/",
    "wework": "https://wework.com/",
    "whatsapp": "https://whatsapp.com/",
    "wikipedia": "https://wikipedia.org/",
    "wise": "https://wise.com/",
    "wordpress": "https://wordpress.com/",
    "x": "https://twitter.com/",
    "yahoo": "https://yahoo.com/",
    "yelp": "https://yelp.com/",
    "yelmo cine": "https://yelmocines.es/",
    "yelmo cines": "https://yelmocines.es/",
    "youtube": "https://www.youtube.com/",
    "youtube kids": "https://youtubekids.com/",
    "zara": "https://zara.com/",
    "zendesk": "https://zendesk.com/",
    "zoho": "https://zoho.com/",
    "zoom": "https://zoom.us/",
    "zoominfo": "https://zoominfo.com/",
    "zomato": "https://zomato.com/",
}
