company_banner = {
    "adobe": "https://asset.brandfetch.io/id_KsyK7J9/idT0XyzQRc.png",
    "adidas": "https://payload.cargocollective.com/1/8/282928/8709412/adidas-banner_1340_c.jpeg",
    "airbnb": "https://asset.brandfetch.io/id_RRaNPJ7/idO3pUk1Dn.jpeg",
    "alcampo": "https://asset.brandfetch.io/id1bUJVxjB/id2ywVIHRU.jpeg",
    "alibaba": "https://asset.brandfetch.io/idlBmDUhAB/idBtuAYdfu.jpeg",
    "aliexpress": "https://asset.brandfetch.io/idonPjBUnw/idXGszlxIt.jpeg",
    "autodesk": "https://asset.brandfetch.io/id_6bobPbH/idv1cp17sm.jpeg",  
    "amazon": "https://asset.brandfetch.io/idawOgYOsG/idDgFxIFL-.jpeg",
    "american express": "https://asset.brandfetch.io/id5WXF6Iyd/id2FEpz6He.jpeg",
    "angellist": "https://asset.brandfetch.io/idwyyZJbe8/idietcpbOU.png",
    "apple": "https://arafatelecom.com/wp-content/uploads/2022/12/brand-banner-apple.jpg",
    "asana": "https://asset.brandfetch.io/idxPi2Evsk/idRnAPWBkc.jpeg",
    "atlassian": "https://asset.brandfetch.io/idlQIwGMOK/id-oeh_yck.png",
    "att": "https://asset.brandfetch.io/id5Kd7HGot/idWoqSyW7h.jpeg",
    "axis bank": "https://asset.brandfetch.io/id78YVtrRp/idSjKwK1i_.jpeg",
    "baidu": "https://techcrunch.com/wp-content/uploads/2014/10/baidu-earnings.png",
    "banco sabadell": "https://media.vozpopuli.com/2024/02/montaje-la-caixa-y-sabadell.jpg",
    "bbva": "https://asset.brandfetch.io/idFaJAazok/idOKEkROCv.jpeg",
    "bbc": "https://wallpapers.com/images/hd/bbc-news-1920-x-1030-background-xdtr035lt8kw9wps.jpg",
    "best buy": "https://asset.brandfetch.io/idmSVs_Vxg/id_m4OVTb2.jpeg",
    "binance": "https://asset.brandfetch.io/id-pjrLx_q/idqVA2j76s.jpeg",
    "blackrock": "https://asset.brandfetch.io/idFVE9LGae/idwvbSRIgs.jpeg",
    "blender": "https://asset.brandfetch.io/id7dDb6peT/idoEkwORZV.jpeg",
    "bloomberg": "https://asset.brandfetch.io/idy68RSCip/id327UzRFq.jpeg",
    "boeing": "https://asset.brandfetch.io/idNLUN4t9U/id7rLOOuZB.jpeg",
    "booking": "https://nariatravel.gr/wp-content/uploads/2017/09/evening-travel-wallpaper-hd-download-free-background-images-amazing-high-definition-4k-2560x1600.jpg",
    "buzzfeed": "https://asset.brandfetch.io/idAMJTgZRM/idMisbXVwi.png",
    "canva": "https://cloudfront-us-east-1.images.arcpublishing.com/corprensa/RVZWBMBFTVECZMQQ6UABUYGZTY.png",
    "carrefour": "https://asset.brandfetch.io/idgBVl3eET/idlhPIAujf.jpeg",
    "cash app": "https://asset.brandfetch.io/idOeoXl-EC/idomvOEZeg.jpeg",
    "chewy": "https://asset.brandfetch.io/idbvs3ZCKi/idKpqm_5q_.jpeg",
    "chime": "https://asset.brandfetch.io/idh8cSYdom/idunh75DHp.jpeg",
    "cine yelmo": "https://wallpapercave.com/wp/wp4016025.jpg", 
    "cinesa": "https://asset.brandfetch.io/idZ1Jz69-u/idVcooaZ0w.jpeg", 
    "cisco": "https://newsroom.cisco.com/c/dam/r/newsroom/en/us/migrated-assets/cl2021_bannerthumb_800x450_2-jpg-2150584-1-0.jpg",
    "citibank": "https://www.wearefreeflow.com/wp-content/uploads/2019/12/citi_credit_card-banner.jpg",
    "clickup": "https://earthtonecontent.com/wp-content/uploads/2023/04/clickup-featurred-image-jpg.webp",
    "cnn": "https://t3.ftcdn.net/jpg/06/61/92/38/360_F_661923888_lpP2DnBnGk8yJre6Gj1nMfBKpjkyGMJm.jpg",
    "coinbase": "https://asset.brandfetch.io/idwDWo4ONQ/idhq4hK9Q2.jpeg",
    "cortefiel": "https://asset.brandfetch.io/idko3ux90s/idFRe7qp8A.jpeg",
    "cura": "https://asset.brandfetch.io/idDw8sEzUK/idbQvj6Jxg.jpeg",
    "columbia": "https://asset.brandfetch.io/idGE3xbU8n/iddxZx9VKg.jpeg",  
    "costco": "https://asset.brandfetch.io/idWtDQZAMc/idP-EwnQ-K.jpeg",
    "coursera": "https://learn-and-grow.hr.ufl.edu/wp-content/uploads/sites/5/2020/05/coursea.jpg",
    "cnbc": "https://m.media-amazon.com/images/I/611MW3x9D2L.jpg",
    "dell": "https://i.dell.com/sites/csimages/App-Merchandizing_Images/all/monitor-buying-guide-hero-desktop-banner_2800x839.jpg",
    "disney": "https://wallpapers.com/images/featured/disney-logo-sw1oz184d480tq37.jpg",
    "disney plus": "https://media.filmelier.com/noticias/mx/2022/03/disney-plus.jpeg",
    "doordash": "https://images.ctfassets.net/4kwp3o37mlek/1Pm2kF58KgUZl51DAyQxGQ/1a4130f3d674032fcaac12597e2af306/AirMiles_DoorDash_Rx-NV-Banner_1280x360.png",
    "dropbox": "https://t4.ftcdn.net/jpg/04/83/62/87/360_F_483628797_CwvimBfwz7bV6lfZBUANn5kXeEf2NKu4.jpg",
    "el corte inglés": "https://www.spain.info/.content/imagenes/cabeceras-grandes/compras/corte-ingles-madrid_c-francesco-cantone_s629348585.jpg",
    "ebay": "https://asset.brandfetch.io/idjTS-RPU1/idZystjHKA.jpeg",
    "etrade": "https://asset.brandfetch.io/idqkyPyVIF/idjyktfd0o.jpeg",
    "etsy": "https://asset.brandfetch.io/idzyTAzn6G/idswDkBaAx.jpeg",
    "evernote": "https://asset.brandfetch.io/idZ_uGTj4S/idSnv9_u87.png",
    "expedia": "https://wallpapercave.com/uwp/uwp3532915.png",
    "facebook": "https://asset.brandfetch.io/idpKX136kp/idJQR2MCtO.jpeg",
    "fedex": "https://asset.brandfetch.io/idVIIZH-LB/idTDNkSjs8.jpeg",
    "fidelity": "https://asset.brandfetch.io/idzIUUVEBm/idlNaVUxku.jpeg",
    "figma": "https://asset.brandfetch.io/idZHcZ_i7F/idMPDVSwsi.jpeg",
    "financial times": "https://asset.brandfetch.io/idpU6ifmxE/id4x-b7F4L.jpeg",
    "fiver": "https://asset.brandfetch.io/idB8OJ7IzV/idA137Nfj5.jpeg",
    "forbes": "https://asset.brandfetch.io/idP48RNgRN/idzVajGJwq.jpeg",
    "genially": "https://asset.brandfetch.io/idaLAHOsk0/ideARrBrsO.jpeg",
    "gemini": "https://asset.brandfetch.io/id08hfGdfR/idwG-0Q06i.jpeg",
    "github": "https://process.fs.teachablecdn.com/ADNupMnWyR7kCWRvm76Laz/resize=width:705/https://cdn.filestackcontent.com/MipxnobQRRS5h7raz9aM",
    "gmail": "https://www.guidingtech.com/wp-content/uploads/How_to_Use_Stars_to_Organize_Your_Emails_in_Gmail.jpg",
    "godaddy": "https://asset.brandfetch.io/idKgLX8HGb/idTmjwC2NU.jpeg",
    "godot": "https://asset.brandfetch.io/iduufsdjZZ/idkumnz7MS.jpeg",
    "godot engine": "https://asset.brandfetch.io/iduufsdjZZ/idkumnz7MS.jpeg",
    "google": "https://wallpapers.com/images/hd/colorful-google-polka-dots-ot2t9bbzehsjggdx.jpg",
    "grubhub": "https://asset.brandfetch.io/idtctBUT8X/idjpLh_OR9.jpeg",
    "harvard": "https://asset.brandfetch.io/idgP1KuU-N/idtgNLXxcL.jpeg",
    "harvard university": "https://asset.brandfetch.io/idgP1KuU-N/idtgNLXxcL.jpeg",
    "hbo": "https://soloencinestv.wordpress.com/wp-content/uploads/2023/01/cropped-hbos-the-last-of-us-banner-v0-3c1iu9tjzr1a1.webp",
    "hbo max": "https://asset.brandfetch.io/idKKo6p4ks/idkfc9vniA.jpeg",
    "hcltech": "https://asset.brandfetch.io/id8i2DmKRE/idXjl_MmRr.jpeg",
    "hdfc bank": "https://asset.brandfetch.io/idxQAAj1t_/idJqV7JtY5.png",
    "huawei": "https://asset.brandfetch.io/idLAJ42baU/id5kdiNkCK.jpeg",
    "hubspot": "https://asset.brandfetch.io/idRt0LuzRf/id_f3_2-NQ.jpeg",
    "hsbc": "https://asset.brandfetch.io/idLLTco_Zw/idJt4Mzegk.jpeg",
    "hulu": "https://wallpapers.com/images/hd/hulu-original-logo-f5l71cwjf41tfyuf.jpg",
    "icici bank": "https://asset.brandfetch.io/idJHpX8apR/idhlBb55Tv.jpeg",
    "ikea": "https://asset.brandfetch.io/idLsXYVLUs/idUIL_oYXo.jpeg",  
    "instagram": "https://asset.brandfetch.io/idDqqvGf2D/idzxLT9HCQ.jpeg",
    "intel": "https://asset.brandfetch.io/idCtsD-GTM/idcwtcUfLI.jpeg",
    "investopedia": "https://asset.brandfetch.io/idVvzxQS87/idPL_kfkEy.jpeg",
    "johnson and johnson": "https://asset.brandfetch.io/idBwyRkMdk/idYyBfTS-g.jpeg",
    "kth":"https://asset.brandfetch.io/idCCf1QEQj/id3AVpK0xe.jpeg",
    "khan academy": "https://asset.brandfetch.io/idPiZnB0IQ/id1NGzUf22.jpeg",
    "kickstarter": "https://asset.brandfetch.io/id77nbwhmq/idnpiy_DgS.jpeg",
    "kpmg": "https://asset.brandfetch.io/id-UmnExAG/ideD0EzFk6.jpeg",
    "kraken": "https://asset.brandfetch.io/idiILtTVLz/idoZL8Zcns.jpeg",
    "lego": "https://www.lego.com/cdn/cs/sustainability/assets/blt1f09ba6deafad51b/earth_videobanner.png?disable=upscale&width=3840&quality=50&crop=15:4",
    "lego house": "https://miro.medium.com/v2/resize:fit:1400/0*IHzToEngNQ_efTDC.png",
    "linkedin": "https://asset.brandfetch.io/idJFz6sAsl/idXyZaUIei.jpeg",
    "lyft": "https://wallpapercave.com/wp/wp4687060.jpg",
    "lufthansa": "https://wallpapercave.com/wp/wp2856756.jpg",
    "marvel": "https://teaser-trailer.com/wp-content/uploads/2017/07/Avengers-Infinity-War-Banner.jpg",
    "mailchimp": "https://asset.brandfetch.io/idMvnv36a4/idSI2lLEex.png",
    "marriott": "https://asset.brandfetch.io/id0DQ-cAhI/idLPUM4fMm.jpeg",
    "marriott bonvoy": "https://asset.brandfetch.io/id0DQ-cAhI/idLPUM4fMm.jpeg",
    "marketwatch": "https://asset.brandfetch.io/idkr23vxEe/id_RlkInvg.jpeg",
    "mastercard": "https://asset.brandfetch.io/idFw8DodCr/idaTV1rZ9h.jpeg",
    "medium": "https://asset.brandfetch.io/idIlQtGZ76/id1Hh80HsC.png",
    "mecabricks": "https://asset.brandfetch.io/id5YIg7QW1/idvQ4dyKeE.jpeg",
    "meta": "https://i.wfcdn.de/teaser/1920/53249.jpg",
    "microsoft": "https://asset.brandfetch.io/idchmboHEZ/idxY0uKEip.jpeg",
    "monday": "https://www.knjiznica-koprivnica.hr/wp-content/uploads/2021/11/Monday.png",
    "morningstar": "https://asset.brandfetch.io/idqGU16uAt/ideW3GNbHc.jpeg",
    "morgan stanley": "https://asset.brandfetch.io/idBGtJQnXa/id4JxSJh8f.jpeg",
    "netflix": "https://wallpapercave.com/wp/wp6889129.jpg",
    "netgear": "https://asset.brandfetch.io/idmaaZurFV/idzLXcujvF.jpeg",
    "the new york times": "https://asset.brandfetch.io/ida5pjO05F/idEKYCPA1z.jpeg",
    "nike": "https://c.static-nike.com/a/images/f_auto,cs_srgb/w_1920,c_limit/tpqid8vgfey6m4ke86te/123-joyride-cdp-apla-xa-xp.jpg",
    "notion": "https://miro.medium.com/v2/resize:fit:1358/1*rwwRfjr4DUYASgLP9gw0rg.png",
    "nvidia": "https://wallpapercave.com/wp/wp10644663.jpg",
    "openbank": "https://s1.elespanol.com/2022/06/22/invertia/empresas/banca/682192111_225274975_1706x960.jpg",
    "oracle": "https://asset.brandfetch.io/idnq7H7qT0/idsKcFn13V.jpeg",
    "outlook": "https://i.wfcdn.de/teaser/1920/39599.jpg",
    "panasonic": "https://asset.brandfetch.io/idZc2Ve3u9/idokejcG9y.jpeg",
    "paypal": "https://wallpapercave.com/wp/wp7443449.jpg",
    "pedro del hierro": "https://www.martinproyectos.com/wp-content/uploads/2018/03/IMG_6677.jpg",  
    "pfizer": "https://wallpapercave.com/wp/wp11790491.jpg",
    "pinterest": "https://asset.brandfetch.io/idB03fsT-Z/idyXnSk4ku.jpeg",
    "pocket": "https://asset.brandfetch.io/idAFQcVY4v/idKgcD00rn.png",
    "postmates": "https://asset.brandfetch.io/idaRpsGay1/idaGaZ3QvJ.jpeg",
    "prime video": "https://m.media-amazon.com/images/G/01/primevideo/seo/primevideo-seo-logo.png",
    "printables": "https://asset.brandfetch.io/idQcCo4q_p/idjbUEeoTC.jpeg",
    "protonmail": "https://asset.brandfetch.io/idXUjI6-Dt/idXGBC_QCY.jpeg",
    "proton mail": "https://asset.brandfetch.io/idXUjI6-Dt/idXGBC_QCY.jpeg",
    "quora": "https://asset.brandfetch.io/idnoi4zGot/id1foCRklD.jpeg",
    "reddit": "https://i.redd.it/ax8u9llk8jy61.jpg",
    "reuters": "https://asset.brandfetch.io/id81tTzGrw/idJVk3Zq6t.jpeg",
    "revolut": "https://www.eleconomista.com.mx/__export/1712619695837/sites/eleconomista/img/2024/04/03/revolut_buena.jpg_1402612189.jpg",
    "robinhood": "https://asset.brandfetch.io/id3WzK3p17/idyepjfuZh.jpeg",
    "rolex": "https://cdn.wallpapersafari.com/3/61/MP15No.jpg",
    "safeway": "https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/52b1b827162895.56360a7162558.jpg",
    "samsung": "https://asset.brandfetch.io/iduaw_nOnR/idrF_fPpjL.jpeg",
    "sdu": "https://www.sdu.dk/-/media/images/service/vejviser/vejviser_sonderborg.jpg?h=375&iar=0&w=870&hash=62FAAC50C0C3A93153F05CE33718E6D0",
    "santander": "https://bordalo.observador.pt/v2/q:84/rs:fill:4096:2303/c:4096:2303:nowe:0:214/plain/https://s3.observador.pt/wp-content/uploads/2021/09/01190139/GettyImages-1309530160-scaled.jpg",
    "shell": "https://asset.brandfetch.io/idBvD8kBit/id9XhEX_mh.jpeg",
    "shopify": "https://wallpapercave.com/wp/wp10267517.jpg",
    "siemens": "https://wallpapercave.com/wp/wp7057400.jpg",
    "skype": "https://wallpapercave.com/wp/wp2100536.jpg",
    "slack": "https://asset.brandfetch.io/idJ_HhtG0Z/idtr3mttVs.png",
    "snapchat": "https://sociality.io/blog/wp-content/uploads/2023/03/insights_SnapchatPlusUltimateGuide.png",
    "sofi": "https://www.investopedia.com/thmb/SkEU81BkqutFtavekkYchYrdMW0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/GettyImages-1246003340-ba73b9f1c9ea4a89941eedf68dc120b7.jpg",
    "sony": "https://images2.alphacoders.com/487/487165.jpg",
    "sothebys": "https://asset.brandfetch.io/idftptCPQi/iddI9TM6kd.jpeg",
    "spacex": "https://asset.brandfetch.io/id2g3lee9x/idyUuqMqfO.jpeg",
    "spotify": "https://cdn.wallpapersafari.com/73/36/kjoK1u.png",
    "square": "https://images.ctfassets.net/2d5q1td6cyxq/2X7RwNTJsJBI5FsLVLtxDw/a34f1ecd9448fa7e8405bbc682855295/Animation_3_outputComp__00000_-PS-2x.png?fm=webp&q=85",
    "starbucks": "https://asset.brandfetch.io/idwBSkfVb3/idlObBirL8.jpeg",
    "stripe": "https://asset.brandfetch.io/idxAg10C0L/idyJBFNKEQ.jpeg",
    "substack": "https://asset.brandfetch.io/id_V6qzrDH/id-EBaQPOK.jpeg",
    "tata": "https://asset.brandfetch.io/idK2mWG2SJ/idHFiskfjR.jpeg",
    "tata consultancies": "https://asset.brandfetch.io/idK2mWG2SJ/idHFiskfjR.jpeg",
    "tata consultancy": "https://asset.brandfetch.io/idK2mWG2SJ/idHFiskfjR.jpeg",
    "tata consultancy services": "https://asset.brandfetch.io/idK2mWG2SJ/idHFiskfjR.jpeg",
    "target": "https://asset.brandfetch.io/id0ZfAM4Dt/idv_rLyClf.jpeg",
    "td ameritrade": "https://asset.brandfetch.io/idn9NyGE6E/idYq21Yxa_.jpeg",
    "tencent": "https://asset.brandfetch.io/idPf1s-Y7S/idyXswA6M4.jpeg",
    "tesla": "https://wallpapercave.com/uwp/uwp4339588.jpeg",
    "the guardian": "https://asset.brandfetch.io/idEaoqZ5uv/id8mFDWbjr.jpeg",
    "the north face": "https://asset.brandfetch.io/idJcrF2oAV/id8fpRp7sG.jpeg",
    "the wall street journal": "https://digiday.com/wp-content/uploads/sites/3/2021/04/WSJ_TYD_OOH-Static-1.jpg",
    "the washington post": "https://www.washingtonpost.com/pb/resources/img/twp-3000x1568.jpg",
    "tinkercad": "https://asset.brandfetch.io/idPimU4oXB/idRxC89Hyg.jpeg",
    "tiktok": "https://wallpapers.com/images/hd/tiktok-logo-patterns-apgm6olmczc7cxq7.jpg",
    "todoist": "https://asset.brandfetch.io/idLi6HZtk-/idoyia3f84.jpeg",
    "toyota": "https://asset.brandfetch.io/idR0dj2M6E/idoXMYXn1p.jpeg",
    "trello": "https://asset.brandfetch.io/idToc8bDY1/idswKY19M1.jpeg",
    "tumblr": "https://wallpapers.com/images/hd/pink-skies-tumblr-cqtrzezrpd3f0w2t.jpg",
    "twitch": "https://asset.brandfetch.io/idIwZCwD2f/ids8zh4byX.png",
    "twilio": "https://images.ctfassets.net/7xchb4r9mgls/5qQmCIhoMWdeSBNgFkVWNJ/47d93c7927dae312d9ab9d537906cef7/what-is-twilio-how-does-it-work.png",
    "twitter": "https://www.adl.org/sites/default/files/images/2023-02/COVER_twitterbirds_1280x720.jpg",
    "uber": "https://asset.brandfetch.io/ididNbiiOd/idTeLZt4O_.jpeg",
    "uber eats": "https://asset.brandfetch.io/idIjpcD2zP/idljpPJjJ5.jpeg",
    "ultimaker": "https://asset.brandfetch.io/idDw8sEzUK/idbQvj6Jxg.jpeg",
    "ultimaker cura": "https://asset.brandfetch.io/idDw8sEzUK/idbQvj6Jxg.jpeg",
    "unreal engine": "https://asset.brandfetch.io/idKDDYCJGJ/idHjI6WKr4.jpeg",
    "ups": "https://asset.brandfetch.io/id5aN1Q7um/idomiSLdSe.jpeg",
    "uptimerobot":"https://asset.brandfetch.io/id9LgS6jeo/idQNtXqNuY.jpeg",
    "vanguard": "https://asset.brandfetch.io/idf3bcOruF/idKzPEtXnR.png",
    "venmo": "https://cdn.wallpapersafari.com/88/66/DZtlHS.jpeg",
    "verizon": "https://asset.brandfetch.io/idXhrQrb5t/idynpJcJ1v.jpeg",
    "vimeo": "https://asset.brandfetch.io/idheAw_tFb/idbpzBcI-L.jpeg",
    "visa": "https://wallpapercave.com/wp/wp4144063.jpg",
    "wall street journal": "https://digiday.com/wp-content/uploads/sites/3/2021/04/WSJ_TYD_OOH-Static-1.jpg",
    "walmart": "https://wallpapers.com/images/hd/walmart-blue-building-o551u681xgjvodsg.jpg",
    "washington post": "https://digiday.com/wp-content/uploads/sites/3/2021/04/WSJ_TYD_OOH-Static-1.jpg",
    "wechat": "https://asset.brandfetch.io/idhIQQJ7ix/idv_Nu7n3R.jpeg",
    "wework": "https://asset.brandfetch.io/id6_LVK2Ng/idsrqIl6JU.jpeg",
    "whatsapp": "https://asset.brandfetch.io/id6Zq084G_/idstxJbhVi.jpeg",
    "wikipedia": "https://asset.brandfetch.io/idAo3WRIoq/idfWk6B34J.jpeg",
    "wise": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Wikipedia20_background_Puzzle_globe.jpg/1920px-Wikipedia20_background_Puzzle_globe.jpg",
    "wordpress": "https://wallpapercave.com/wp/wp6905489.jpg",
    "x": "https://9to5mac.com/wp-content/uploads/sites/6/2023/07/Twitter-X.jpg?quality=82&strip=all",
    "yahoo": "https://wallpapercave.com/wp/wp4144448.jpg",
    "yelp": "https://asset.brandfetch.io/idvwtgSsRX/idViqg5jOR.jpeg",
    "yelmo cine": "https://wallpapercave.com/wp/wp4016025.jpg",
    "yelmo cines": "https://wallpapercave.com/wp/wp4016025.jpg",
    "youtube": "https://images8.alphacoders.com/109/1094155.jpg",
    "youtube kids": "https://images.squarespace-cdn.com/content/v1/51f94ebfe4b022983127537c/1562836604336-FZ835LS3DIB9JGTOUKMK/ytk-header.jpg?format=2500w",
    "zara": "https://asset.brandfetch.io/id96Nz75pK/idTDMfaMcz.jpeg",
    "zendesk": "https://asset.brandfetch.io/idNq8SRGPd/idTg8FKAfy.jpeg",
    "zoho": "https://asset.brandfetch.io/idssig0_jY/idoALzodXH.jpeg",
    "zoom": "https://i.etsystatic.com/30702781/r/il/f1ee97/5586517529/il_fullxfull.5586517529_olyi.jpg",
    "zoominfo": "https://cxscoop.com/wp-content/uploads/2023/02/ZoomInfo-to-Integrate-GPT-Into-Its-Platform.png",
    "zomato": "https://wallpapercave.com/wp/wp9980760.jpg",
}
