# Go to (https://brandfetch.com/) to get more logos, the API service has a limit.

company_logos = {
    "adobe": "https://asset.brandfetch.io/id_KsyK7J9/idk8IZnNuj.svg",
    "adidas": "https://asset.brandfetch.io/id8Pwl3kos/id2CYeOYhk.svg",
    "airbnb": "https://asset.brandfetch.io/idkuvXnjOH/idZUWqJuSO.svg",
    "alcampo": "https://asset.brandfetch.io/id1bUJVxjB/idTbv8GQNq.svg",
    "alibaba": "https://asset.brandfetch.io/idmN3dKMN4/id2d7q87l-.svg",
    "aliexpress": "https://asset.brandfetch.io/idonPjBUnw/idE-6k4rj1.svg",
    "autodesk": "https://asset.brandfetch.io/id_6bobPbH/idt11I-IAL.svg",  
    "amazon": "https://asset.brandfetch.io/idawOgYOsG/idisSB3V3T.svg",
    "american express": "https://asset.brandfetch.io/id5WXF6Iyd/idVmVjWLQF.svg",
    "angellist": "https://asset.brandfetch.io/idwyyZJbe8/idgcOp7xVM.svg",
    "apple": "https://asset.brandfetch.io/idnrCPuv87/idSimOayjK.svg",
    "asana": "https://asset.brandfetch.io/idxPi2Evsk/idXp3_6g45.svg",
    "atlassian": "https://asset.brandfetch.io/idlQIwGMOK/id-zfVoXlz.svg",
    "att": "https://asset.brandfetch.io/id5Kd7HGot/idCT6kZn7Y.svg",
    "axis bank": "https://asset.brandfetch.io/id78YVtrRp/id-I9oK5CT.svg",
    "baidu": "https://asset.brandfetch.io/idE170FN48/idQlVL0fek.svg",
    "banco sabadell": "https://asset.brandfetch.io/idCFRqA_TO/idxAr3tdgy.svg",
    "bbva": "https://asset.brandfetch.io/idFaJAazok/idcml6-YqU.svg",
    "bbc": "https://asset.brandfetch.io/idtEghWGp4/id_fFh3BjE.svg",
    "best buy": "https://asset.brandfetch.io/idmSVs_Vxg/id8D8byKAd.svg",
    "binance": "https://asset.brandfetch.io/id-pjrLx_q/idlT6o-c2Q.svg",
    "blackrock": "https://asset.brandfetch.io/idFVE9LGae/idvoZpgtn9.svg",
    "blender": "https://asset.brandfetch.io/id7dDb6peT/idzOtL_q-z.svg",
    "bloomberg": "https://asset.brandfetch.io/idy68RSCip/idJqNHORrP.svg",
    "boeing": "https://asset.brandfetch.io/idzTkfG2gL/idvtOm7fmM.png",
    "booking": "https://asset.brandfetch.io/id9mEmLNcV/idtpV9y0Bb.svg",
    "buzzfeed": "https://asset.brandfetch.io/idwHmTJPBC/id5Dlc349O.svg",
    "canva": "https://asset.brandfetch.io/id9mVQlyB1/idYpWK1qjb.svg",
    "carrefour": "https://asset.brandfetch.io/idgBVl3eET/id7tQIg9Y0.svg",
    "cash app": "https://asset.brandfetch.io/idOeoXl-EC/idxEM29Dx_.svg",
    "chewy": "https://asset.brandfetch.io/idbvs3ZCKi/id1D2XedmF.svg",
    "chime": "https://asset.brandfetch.io/idh8cSYdom/idT_u9y5YE.svg",
    "cine yelmo": "https://asset.brandfetch.io/id_H8GRRwx/idjfBZz_pE.svg",  
    "cinesa": "https://asset.brandfetch.io/idZ1Jz69-u/id5Pu-NaL5.svg",      
    "cisco": "https://asset.brandfetch.io/ida_xaMYlM/idvOp3xhr4.svg",
    "citibank": "https://asset.brandfetch.io/idr8xpMOko/id5CFGcxw1.svg",
    "clickup": "https://asset.brandfetch.io/idU6lzwMYA/idG3mdUrjZ.svg",
    "cnn": "https://asset.brandfetch.io/idhidc5593/idPiQCIcUy.svg",
    "coinbase": "https://asset.brandfetch.io/idwDWo4ONQ/idPC-FAZPh.svg",
    "cortefiel": "https://asset.brandfetch.io/idko3ux90s/idGa_pLGBG.svg",
    "cura": "https://asset.brandfetch.io/idDw8sEzUK/idiAjAnRRs.png",
    "columbia": "https://asset.brandfetch.io/idGE3xbU8n/idWHam9Vra.svg",
    "costco": "https://asset.brandfetch.io/idWtDQZAMc/idHJnJuQ20.svg",
    "coursera": "https://asset.brandfetch.io/idTHfL51P-/idT-W75eGM.svg",
    "cnbc": "https://asset.brandfetch.io/iddr-Ds11g/idfjsS8psC.svg",
    "dell": "https://asset.brandfetch.io/idc1hWCJYN/idM8cg87co.svg",
    "disney": "https://asset.brandfetch.io/idxASqzkm_/idVABj3eyR.svg",
    "disney plus": "https://asset.brandfetch.io/idhQlYRiX2/idtmkrxMme.svg",
    "doordash": "https://asset.brandfetch.io/idrVhdDocf/idot6CRBLZ.svg",
    "dropbox": "https://asset.brandfetch.io/idY3kwH_Nx/idpEif7tzn.svg",
    "el corte inglés": "https://asset.brandfetch.io/idh21rHw8g/idIZd_wA0U.svg",
    "ebay": "https://asset.brandfetch.io/idjTS-RPU1/ideoRL0Xqo.svg",
    "etrade": "https://asset.brandfetch.io/idqkyPyVIF/id0ULjkc1k.svg",
    "etsy": "https://asset.brandfetch.io/idzyTAzn6G/idpMsMX5yq.svg",
    "evernote": "https://asset.brandfetch.io/idZ_uGTj4S/idN2kyIF2e.svg",
    "expedia": "https://asset.brandfetch.io/idAGaivHFH/idh0A6Q8p0.svg",
    "facebook": "https://asset.brandfetch.io/idpKX136kp/idH4d4VH7v.svg",
    "fedex": "https://asset.brandfetch.io/idVIIZH-LB/idjrOV7l9b.svg",
    "fidelity": "https://asset.brandfetch.io/idzIUUVEBm/id_EOknnqb.svg",
    "figma": "https://asset.brandfetch.io/idZHcZ_i7F/idmRT2A2yv.svg",
    "financial times": "https://asset.brandfetch.io/idpU6ifmxE/idkUptO7Ha.svg",
    "fiver": "https://asset.brandfetch.io/idB8OJ7IzV/idpsSEPbqz.svg",
    "forbes": "https://asset.brandfetch.io/idP48RNgRN/idyfVBs-Wp.svg",
    "genially": "https://asset.brandfetch.io/idaLAHOsk0/idnzpqnq77.svg",
    "gemini": "https://asset.brandfetch.io/id08hfGdfR/idFI2yc4PE.svg",
    "github": "https://asset.brandfetch.io/idZAyF9rlg/idyBTsqLzR.svg",
    "gmail": "https://asset.brandfetch.io/id5o3EIREg/idZ-6Zk9-C.svg",
    "godaddy": "https://asset.brandfetch.io/idKgLX8HGb/idY04IMYMU.svg",
    "godot": "https://asset.brandfetch.io/iduufsdjZZ/idDNKt9e8p.svg",
    "godot engine": "https://asset.brandfetch.io/iduufsdjZZ/idDNKt9e8p.svg",
    "google": "https://asset.brandfetch.io/id6O2oGzv-/idP6g0Ep4y.svg",
    "grubhub": "https://asset.brandfetch.io/idtctBUT8X/id2LENoj_F.svg",
    "harvard": "https://asset.brandfetch.io/idgP1KuU-N/idJmgAce_I.svg",
    "harvard university": "https://asset.brandfetch.io/idgP1KuU-N/idJmgAce_I.svg",
    "hbo": "https://asset.brandfetch.io/ide9_vzBKU/id8g7EYt7E.svg",
    "hbo max": "https://asset.brandfetch.io/idKKo6p4ks/id5j1VlY0X.svg",
    "hcltech": "https://asset.brandfetch.io/id8i2DmKRE/idi5w2cr2q.svg",
    "hdfc bank": "https://asset.brandfetch.io/idxQAAj1t_/idrxvKia3R.svg",
    "huawei": "https://asset.brandfetch.io/idLAJ42baU/idmlSjh_g5.png",
    "hubspot": "https://asset.brandfetch.io/idRt0LuzRf/id_Ox3lZVa.svg",
    "hsbc": "https://asset.brandfetch.io/idLLTco_Zw/idpShkJ2yo.svg",
    "hulu": "https://asset.brandfetch.io/id4KRloCCr/id3LeKwEqc.svg",
    "icici bank": "https://asset.brandfetch.io/idJHpX8apR/id7HFP9fq3.svg",
    "ikea": "https://asset.brandfetch.io/idLsXYVLUs/idyELJM6NZ.svg",  
    "instagram": "https://asset.brandfetch.io/ido5G85nya/idVNVClIoG.svg",
    "intel": "https://asset.brandfetch.io/idTGhLyv09/idfv3nRlFj.svg",
    "investopedia": "https://asset.brandfetch.io/idVvzxQS87/idmgCJV_GJ.svg",
    "johnson and johnson": "https://asset.brandfetch.io/idBwyRkMdk/id3OSGrzyr.svg",
    "kth":"https://asset.brandfetch.io/idCCf1QEQj/idC7JbsDRl.svg",
    "khan academy": "https://asset.brandfetch.io/idPiZnB0IQ/idRkY1-HdG.png",
    "kickstarter": "https://asset.brandfetch.io/id77nbwhmq/id_9UXkqc7.svg",
    "kpmg": "https://asset.brandfetch.io/id-UmnExAG/idp3OhaAhl.svg",
    "kraken": "https://asset.brandfetch.io/idYQrXoH-Q/idCQMG-KZy.svg",
    "lego": "https://asset.brandfetch.io/idmoRM4Wwz/idWqEf5vck.jpeg",
    "lego house": "https://asset.brandfetch.io/idrSpWVUTe/idnXb0PASi.png",
    "linkedin": "https://asset.brandfetch.io/idJFz6sAsl/idZ43Jg46z.svg",
    "lyft": "https://asset.brandfetch.io/idF3tki5X5/idLsGba5N3.svg",
    "lufthansa": "https://asset.brandfetch.io/id1SLeDvgF/idEZioPTGE.svg",
    "marvel": "https://asset.brandfetch.io/idaI8wwJGu/idShpyAbCv.svg",
    "mailchimp": "https://asset.brandfetch.io/idMvnv36a4/idbiyBBgqE.svg",
    "marriott": "https://asset.brandfetch.io/id0DQ-cAhI/idHaBuKzyO.svg",
    "marriott bonvoy": "https://asset.brandfetch.io/id0DQ-cAhI/idHaBuKzyO.svg",
    "marketwatch": "https://asset.brandfetch.io/idkr23vxEe/idcWdSkvoL.svg",
    "mastercard": "https://asset.brandfetch.io/idFw8DodCr/idAtuP2adk.svg",
    "medium": "https://asset.brandfetch.io/idIlQtGZ76/idSKBZBgqc.svg",
    "mecabricks": "https://asset.brandfetch.io/id5YIg7QW1/idRCvS7bmN.png",
    "meta": "https://upload.wikimedia.org/wikipedia/commons/7/7b/Meta_Platforms_Inc._logo.svg",
    "microsoft": "https://asset.brandfetch.io/idchmboHEZ/idDBL6fNkv.svg",
    "monday": "https://asset.brandfetch.io/idHFUcTb1F/idG68R3Vny.svg",
    "morningstar": "https://asset.brandfetch.io/idqGU16uAt/id3uh0cNVN.svg",
    "morgan stanley": "https://asset.brandfetch.io/idBGtJQnXa/idrxu5hAXs.svg",
    "netflix": "https://asset.brandfetch.io/ideQwN5lBE/id4qnE0Mvj.svg",
    "netgear": "https://asset.brandfetch.io/idmaaZurFV/idKbwLHY_t.svg",
    "the new york times": "https://asset.brandfetch.io/ida5pjO05F/idT2FR40Df.svg",
    "nike": "https://asset.brandfetch.io/id_0dwKPKT/id8PORLc73.svg",
    "notion": "https://asset.brandfetch.io/idPYUoikV7/id-TDv2-jo.svg",
    "nvidia": "https://asset.brandfetch.io/idXoj5DuCE/idBw4kYmoE.svg",
    "openbank": "https://asset.brandfetch.io/idxRQDDcZn/idbMQgCkoI.svg",
    "oracle": "https://asset.brandfetch.io/idnq7H7qT0/ideifBVrAL.svg",
    "outlook": "https://asset.brandfetch.io/idosUKQbqO/idMid1peP1.svg",
    "panasonic": "https://asset.brandfetch.io/idZc2Ve3u9/idK16aYN-b.svg",
    "paypal": "https://asset.brandfetch.io/id-Wd4a4TS/id4wNJYpBf.svg",
    "pedro del hierro": "https://asset.brandfetch.io/id4GTHqHOX/idH9Hmj991.svg",  
    "pfizer": "https://asset.brandfetch.io/idiBxFRhd9/ido439HBxO.svg",
    "pinterest": "https://asset.brandfetch.io/idGP0S1Jjj/idrcPTMuDp.svg",
    "pocket": "https://asset.brandfetch.io/idAFQcVY4v/idEcfdw2rU.png",
    "postmates": "https://asset.brandfetch.io/idaRpsGay1/idTz8wlkH1.svg",
    "prime video": "https://asset.brandfetch.io/idXRXV6qi8/ido-v9m7iu.png",
    "printables": "https://asset.brandfetch.io/idQcCo4q_p/id6Crrb1V7.png",
    "protonmail": "https://asset.brandfetch.io/idDuXugqjZ/idAlqUoV9U.svg",
    "proton mail": "https://asset.brandfetch.io/idDuXugqjZ/idAlqUoV9U.svg",
    "quora": "https://asset.brandfetch.io/idnoi4zGot/idXl7P9R0t.svg",
    "reddit": "https://asset.brandfetch.io/idkKwm0IT0/idy-JEKPXD.svg",
    "reuters": "https://asset.brandfetch.io/id81tTzGrw/idw1xSVWt8.svg",
    "revolut": "https://asset.brandfetch.io/idkTaHd18D/idtoJdlVD8.svg",
    "robinhood": "https://asset.brandfetch.io/id3WzK3p17/idP0gmgs4t.svg",
    "rolex": "https://asset.brandfetch.io/id6o4BHTpv/idY6YwoVwN.svg",
    "safeway": "https://asset.brandfetch.io/ida-1VrFBc/idF6NI8HQG.svg",
    "samsung": "https://asset.brandfetch.io/iduaw_nOnR/idAJ3_YwNM.svg",
    "santander": "https://asset.brandfetch.io/idonugKn4x/idsvUSTgwn.svg",
    "sdu":"https://asset.brandfetch.io/idmqIp-un9/idgljw0xIn.svg",
    "shell": "https://asset.brandfetch.io/idBvD8kBit/idXJslcKum.svg",
    "shopify": "https://asset.brandfetch.io/idAgPm7IvG/ide35ms0Ll.svg",
    "siemens": "https://asset.brandfetch.io/idtwZZpkvB/idQCRcggTQ.svg",
    "skype": "https://asset.brandfetch.io/idnHnk2HwQ/idT_1kjgAa.svg",
    "slack": "https://asset.brandfetch.io/idJ_HhtG0Z/idaPaNYhFw.svg",
    "snapchat": "https://asset.brandfetch.io/id4VHp4_C_/idWWUbeG5U.svg",
    "sofi": "https://asset.brandfetch.io/idtFgUuCT8/id-zGK4nRu.svg",
    "sony": "https://asset.brandfetch.io/ido0LYg_hc/idbW_DO1nX.svg",
    "sothebys": "https://asset.brandfetch.io/idftptCPQi/id-ZE9ZSuP.svg",
    "spacex": "https://asset.brandfetch.io/id2g3lee9x/idtLHGI9WB.svg",
    "spotify": "https://asset.brandfetch.io/id20mQyGeY/id_FyKD1GS.svg",
    "square": "https://asset.brandfetch.io/idyxZCX73R/idVBUxlM3x.svg",
    "starbucks": "https://asset.brandfetch.io/idwBSkfVb3/id6PMjWJJo.svg",
    "stripe": "https://asset.brandfetch.io/idxAg10C0L/idATb3amIw.svg",
    "substack": "https://asset.brandfetch.io/id_V6qzrDH/idCR5ptyYI.png",
    "tata": "https://asset.brandfetch.io/idK2mWG2SJ/idDJUOk-Io.svg",
    "tata consultancies": "https://asset.brandfetch.io/idK2mWG2SJ/idDJUOk-Io.svg",
    "tata consultancy": "https://asset.brandfetch.io/idK2mWG2SJ/idDJUOk-Io.svg",
    "tata consultancy services": "https://asset.brandfetch.io/idK2mWG2SJ/idDJUOk-Io.svg",
    "target": "https://asset.brandfetch.io/id0ZfAM4Dt/idir-jGybn.svg",
    "td ameritrade": "https://asset.brandfetch.io/idn9NyGE6E/idbhVcVqvP.svg",
    "tencent": "https://asset.brandfetch.io/idPf1s-Y7S/idxkKmXv_x.svg",
    "tesla": "https://asset.brandfetch.io/id2S-kXbuK/idAJ5NMLPG.svg",
    "the guardian": "https://asset.brandfetch.io/idEaoqZ5uv/idgKO78yUR.svg",
    "the north face": "https://asset.brandfetch.io/idJcrF2oAV/idIF7-7IGN.svg",
    "the wall street journal": "https://asset.brandfetch.io/id2MIZw9Ti/id4bG3n8QO.svg",
    "the washington post": "https://asset.brandfetch.io/id0DOFivOX/idUNgfXmVW.svg",
    "tiktok": "https://asset.brandfetch.io/id-0D6OFrq/idcl-f98QJ.svg",
    "tinkercad": "https://asset.brandfetch.io/idPimU4oXB/idh4AraB3e.svg",
    "todoist": "https://asset.brandfetch.io/idLi6HZtk-/idGl24L2tz.png",
    "toyota": "https://asset.brandfetch.io/idR0dj2M6E/idYcz3_hF6.svg",
    "trello": "https://asset.brandfetch.io/idToc8bDY1/idWzvpTN85.svg",
    "tumblr": "https://asset.brandfetch.io/idOm3KEKVV/idhbfPpoUf.svg",
    "twitch": "https://asset.brandfetch.io/idIwZCwD2f/id1T3V7cup.svg",
    "twilio": "https://asset.brandfetch.io/idT7wVo_zL/idv6P5GaJs.svg",
    "twitter": "https://asset.brandfetch.io/idS5WhqBbM/id-opmlNbH.svg",
    "uber": "https://asset.brandfetch.io/ididNbiiOd/idwIoriw8o.svg",
    "uber eats": "https://asset.brandfetch.io/idIjpcD2zP/idT_4VNf_n.svg",
    "ultimaker": "https://asset.brandfetch.io/idDw8sEzUK/idiAjAnRRs.png",
    "ultimaker cura": "https://asset.brandfetch.io/idDw8sEzUK/idiAjAnRRs.png",
    "unreal engine": "https://asset.brandfetch.io/idKDDYCJGJ/id1YKtnqr4.svg",
    "ups": "https://asset.brandfetch.io/id5aN1Q7um/idWpm1ptPl.svg",
    "uptimerobot": "https://www.pagerduty.com/wp-content/uploads/2021/03/uptimerobot-logo-09.png",
    "vanguard": "https://asset.brandfetch.io/idf3bcOruF/id1X7dmg91.svg",
    "venmo": "https://asset.brandfetch.io/idzxDKVd5k/id6Bp5prj6.svg",
    "verizon": "https://asset.brandfetch.io/idXhrQrb5t/idBGE2Ipx8.svg",
    "vimeo": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Vimeo_Logo.svg/1280px-Vimeo_Logo.svg.png",
    "visa": "https://asset.brandfetch.io/idhem73aId/id7B1VUknk.svg",
    "wall street journal": "https://asset.brandfetch.io/id2MIZw9Ti/id4bG3n8QO.svg",
    "walmart": "https://asset.brandfetch.io/idoGsFQrHx/idj6l2yMxj.svg",
    "washington post": "https://asset.brandfetch.io/id0DOFivOX/idUNgfXmVW.svg",
    "wechat": "https://asset.brandfetch.io/idhIQQJ7ix/id6FC7m33s.svg",
    "wework": "https://asset.brandfetch.io/id6_LVK2Ng/idPt4abbBc.svg",
    "whatsapp": "https://asset.brandfetch.io/id6Zq084G_/idTz6Pje49.svg",
    "wikipedia": "https://asset.brandfetch.io/idAo3WRIoq/idpY-V37uF.svg",
    "wise": "https://asset.brandfetch.io/idk6fxo1w1/idTi1cUJMt.svg",
    "wordpress": "https://asset.brandfetch.io/idbnlnCBDY/idVOB5r3Nv.svg",
    "x": "https://asset.brandfetch.io/idS5WhqBbM/id-opmlNbH.svg",
    "yahoo": "https://asset.brandfetch.io/idgoJtPkpl/idGA9wfHeu.svg",
    "yelp": "https://asset.brandfetch.io/idvwtgSsRX/idESHQtUtB.svg",
    "yelmo cine": "https://asset.brandfetch.io/id_H8GRRwx/idjfBZz_pE.svg",
    "yelmo cines": "https://asset.brandfetch.io/id_H8GRRwx/idjfBZz_pE.svg",
    "youtube": "https://asset.brandfetch.io/idVfYwcuQz/idjJfigk8Y.svg",
    "youtube kids": "https://asset.brandfetch.io/idroiQwnI1/idHBIfsrGC.svg",
    "zara": "https://asset.brandfetch.io/id96Nz75pK/idbfoY6vv8.svg",
    "zendesk": "https://asset.brandfetch.io/idNq8SRGPd/idtkWWsx7f.svg",
    "zoho": "https://asset.brandfetch.io/idssig0_jY/idxAnBPcQE.svg",
    "zoom": "https://asset.brandfetch.io/id3aO4Szj3/id_OHhUCAK.svg",
    "zoominfo": "https://asset.brandfetch.io/idRcifJ0pN/idgV4kpiVA.svg",
    "zomato": "https://asset.brandfetch.io/idEql8nEWn/idNVDZqdhh.svg",
}
