company_categories = {
    "adobe": "Technology",
    "adidas": "Retail",
    "airbnb": "Travel & Transport",
    "alcampo": "Retail",
    "alibaba": "Retail",
    "aliexpress": "Retail",
    "autodesk": "Technology",
    "amazon": "Retail",
    "american express": "Finance",
    "angellist": "Finance",
    "apple": "Technology",
    "asana": "Technology",
    "atlassian": "Technology",
    "att": "Technology",
    "axis bank": "Finance",
    "baidu": "Technology",
    "banco sabadell": "Finance",
    "bbva": "Finance",
    "bbc": "News & Media",
    "best buy": "Retail",
    "binance": "Finance",
    "blackrock": "Finance",
    "blender": "Technology",
    "bloomberg": "News & Media",
    "boeing": "Travel & Transport",
    "booking": "Travel & Transport",
    "buzzfeed": "News & Media",
    "canva": "Technology",
    "carrefour": "Retail",
    "cash app": "Finance",
    "chewy": "Retail",
    "chime": "Finance",
    "cine yelmo": "Entertainment",
    "cinesa": "Entertainment",
    "cisco": "Technology",
    "citibank": "Finance",
    "clickup": "Technology",
    "cnn": "News & Media",
    "coinbase": "Finance",
    "cortefiel": "Retail",
    "cura": "Technology",
    "columbia": "Retail",
    "costco": "Retail",
    "coursera": "Education",
    "cnbc": "News & Media",
    "dell": "Technology",
    "disney": "Entertainment",
    "disney plus": "Entertainment",
    "doordash": "Travel & Transport",
    "dropbox": "Technology",
    "el corte inglés": "Retail",
    "ebay": "Retail",
    "etrade": "Finance",
    "etsy": "Retail",
    "evernote": "Technology",
    "expedia": "Travel & Transport",
    "facebook": "News & Media",
    "fedex": "Travel & Transport",
    "fidelity": "Finance",
    "figma": "Technology",
    "financial times": "News & Media",
    "fiver": "Technology",
    "forbes": "News & Media",
    "genially": "Technology",
    "gemini": "Finance",
    "github": "Technology",
    "gmail": "Technology",
    "godaddy": "Technology",
    "godot": "Technology",
    "godot engine": "Technology",
    "google": "Technology",
    "grubhub": "Travel & Transport",
    "harvard": "Education",
    "harvard university": "Education",
    "hbo": "Entertainment",
    "hbo max": "Entertainment",
    "hcltech": "Technology",
    "hdfc bank": "Finance",
    "huawei": "Technology",
    "hubspot": "Technology",
    "hsbc": "Finance",
    "hulu": "Entertainment",
    "icici bank": "Finance",
    "ikea": "Retail",
    "instagram": "News & Media",
    "intel": "Technology",
    "investopedia": "News & Media",
    "johnson and johnson": "Technology",
    "kth":"Education",
    "khan academy": "Education",
    "kickstarter": "Finance",
    "kpmg": "Finance",
    "kraken": "Finance",
    "lego": "Retail",
    "lego house": "Entertainment",
    "linkedin": "News & Media",
    "lyft": "Travel & Transport",
    "lufthansa": "Travel & Transport",
    "marvel": "Entertainment",
    "mailchimp": "Technology",
    "marriott": "Travel & Transport",
    "marriott bonvoy": "Travel & Transport",
    "marketwatch": "News & Media",
    "mastercard": "Finance",
    "medium": "News & Media",
    "mecabricks": "Technology",
    "meta": "Technology",
    "microsoft": "Technology",
    "monday": "Technology",
    "morningstar": "Finance",
    "morgan stanley": "Finance",
    "netflix": "Entertainment",
    "netgear": "Technology",
    "the new york times": "News & Media",
    "nike": "Retail",
    "notion": "Technology",
    "nvidia": "Technology",
    "openbank": "Finance",
    "oracle": "Technology",
    "outlook": "Technology",
    "panasonic": "Technology",
    "paypal": "Finance",
    "pedro del hierro": "Retail",
    "pfizer": "Technology",
    "pinterest": "News & Media",
    "pocket": "Technology",
    "postmates": "Travel & Transport",
    "prime video": "Entertainment",
    "printables": "Technology",
    "protonmail": "Technology",
    "proton mail": "Technology",
    "quora": "News & Media",
    "reddit": "News & Media",
    "reuters": "News & Media",
    "revolut": "Finance",
    "robinhood": "Finance",
    "rolex": "Retail",
    "safeway": "Retail",
    "samsung": "Technology",
    "santander": "Finance",
    "sdu": "Education",
    "shell": "Technology",
    "shopify": "Retail",
    "siemens": "Technology",
    "skype": "Technology",
    "slack": "Technology",
    "snapchat": "News & Media",
    "sofi": "Finance",
    "sony": "Technology",
    "sothebys": "Retail",
    "spacex": "Technology",
    "spotify": "Entertainment",
    "square": "Finance",
    "starbucks": "Retail",
    "stripe": "Finance",
    "substack": "News & Media",
    "tata": "Technology",
    "tata consultancies": "Technology",
    "tata consultancy": "Technology",
    "tata consultancy services": "Technology",
    "target": "Retail",
    "td ameritrade": "Finance",
    "tencent": "Technology",
    "tesla": "Technology",
    "the guardian": "News & Media",
    "the north face": "Retail",
    "the wall street journal": "News & Media",
    "the washington post": "News & Media",
    "tiktok": "News & Media",
    "tinkercad": "Technology",
    "todoist": "Technology",
    "toyota": "Technology",
    "trello": "Technology",
    "tumblr": "News & Media",
    "twitch": "Entertainment",
    "twilio": "Technology",
    "twitter": "News & Media",
    "uber": "Travel & Transport",
    "uber eats": "Travel & Transport",
    "ultimaker": "Technology",
    "ultimaker cura": "Technology",
    "unreal engine": "Technology",
    "ups": "Travel & Transport",
    "vanguard": "Finance",
    "venmo": "Finance",
    "verizon": "Technology",
    "vimeo": "Entertainment",
    "visa": "Finance",
    "wall street journal": "News & Media",
    "walmart": "Retail",
    "washington post": "News & Media",
    "wechat": "News & Media",
    "wework": "Technology",
    "whatsapp": "News & Media",
    "wikipedia": "Education",
    "wise": "Finance",
    "wordpress": "Technology",
    "x": "News & Media",
    "yahoo": "Technology",
}
