
    const backgroundCombinations = {
        Blue: {
            backgroundClass2: 'change-Lblue',
            backgroundClass3: 'change-Dblue'
        },
        Teal: {
            backgroundClass2: 'change-Lteal',
            backgroundClass3: 'change-Dteal'
        },
        Black: {
            backgroundClass2: 'change-Lblack',
            backgroundClass3: 'change-Dblack'
        },
        Brown: {
            backgroundClass2: 'change-Lbrown',
            backgroundClass3: 'change-Dbrown'
        },
        Teak: {
            backgroundClass2: 'change-Lteak',
            backgroundClass3: 'change-Dteak'
        },
        DarkGreen: {
            backgroundClass2: 'change-Ldarkgreen',
            backgroundClass3: 'change-Ddarkgreen'
        },
        Green: {
            backgroundClass2: 'change-Lgreen',
            backgroundClass3: 'change-Dgreen'
        },
        Orange: {
            backgroundClass2: 'change-Lorange',
            backgroundClass3: 'change-Dorange'
        },
        DarkOrange: {
            backgroundClass2: 'change-Ldarkorange',
            backgroundClass3: 'change-Ddarkorange'
        },
        NeonOrange: {
            backgroundClass2: 'change-Lneonorange',
            backgroundClass3: 'change-Dneonorange'
        },
        Pink: {
            backgroundClass2: 'change-Lpink',
            backgroundClass3: 'change-Dpink'
        },
        Purple: {
            backgroundClass2: 'change-Lpurple',
            backgroundClass3: 'change-Dpurple'
        },
        DarkRed: {
            backgroundClass2: 'change-Ldarkred',
            backgroundClass3: 'change-Ddarkred'
        },
        Rausch: {
            backgroundClass2: 'change-Lrausch',
            backgroundClass3: 'change-Drausch'
        },
        Red: {
            backgroundClass2: 'change-Lred',
            backgroundClass3: 'change-Dred'
        },
        Gold: {
            backgroundClass2: 'change-Lgold',
            backgroundClass3: 'change-Dgold'
        },
        Lime: {
            backgroundClass2: 'change-Llime',
            backgroundClass3: 'change-Dlime'
        },
        Yellow: {
            backgroundClass2: 'change-Lyellow',
            backgroundClass3: 'change-Dyellow'
        }
        // Add more combinations as needed
    };
    
    const companyConfig = {
        adobe: backgroundCombinations.Red,
        adidas: backgroundCombinations.Blue,
        airbnb: backgroundCombinations.Rausch,
        alcampo: backgroundCombinations.Red,
        alibaba: backgroundCombinations.DarkOrange,
        aliexpress: backgroundCombinations.Red,
        autodesk: backgroundCombinations.Black,
        amazon: backgroundCombinations.Orange,
        "american express": backgroundCombinations.Blue,
        angellist: backgroundCombinations.Black,
        apple: backgroundCombinations.Black,
        asana: backgroundCombinations.Rausch,
        atlassian: backgroundCombinations.Blue,
        att: backgroundCombinations.Blue,
        "axis bank": backgroundCombinations.DarkRed,
        baidu: backgroundCombinations.Blue,
        "banco sabadell": backgroundCombinations.Blue,
        bbva: backgroundCombinations.Blue,
        bbc: backgroundCombinations.Red,
        "best buy": backgroundCombinations.Blue,
        binance: backgroundCombinations.Gold,
        blackrock: backgroundCombinations.Black,
        blender: backgroundCombinations.Orange,
        bloomberg: backgroundCombinations.Black,
        boeing: backgroundCombinations.Blue,
        booking: backgroundCombinations.Blue,
        buzzfeed: backgroundCombinations.Red,
        canva: backgroundCombinations.Purple,
        carrefour: backgroundCombinations.Blue,
        "cash app": backgroundCombinations.Green,
        chewy: backgroundCombinations.Blue,
        chime: backgroundCombinations.Green,
        "cine yelmo": backgroundCombinations.DarkRed,
        cinesa: backgroundCombinations.Yellow,
        cisco: backgroundCombinations.Blue,
        citibank: backgroundCombinations.Blue,
        clickup: backgroundCombinations.Purple,
        cnn: backgroundCombinations.Red,
        coinbase: backgroundCombinations.Blue,
        cortefiel: backgroundCombinations.Black,
        cura: backgroundCombinations.Blue,
        columbia: backgroundCombinations.Blue,
        costco: backgroundCombinations.DarkRed,
        coursera: backgroundCombinations.Blue,
        cnbc: backgroundCombinations.Blue,
        dell: backgroundCombinations.Blue,
        disney: backgroundCombinations.Blue,
        "disney plus": backgroundCombinations.Blue,
        doordash: backgroundCombinations.Red,
        dropbox: backgroundCombinations.Blue,
        "el corte inglés": backgroundCombinations.DarkGreen,
        ebay: backgroundCombinations.Blue,
        etrade: backgroundCombinations.Purple,
        etsy: backgroundCombinations.Orange,
        evernote: backgroundCombinations.Green,
        expedia: backgroundCombinations.Blue,
        facebook: backgroundCombinations.Blue,
        fedex: backgroundCombinations.Purple,
        fidelity: backgroundCombinations.Green,
        figma: backgroundCombinations.Purple,
        "financial times": backgroundCombinations.Teak,
        fiver: backgroundCombinations.Green,
        forbes: backgroundCombinations.Black,
        genially: backgroundCombinations.Blue,
        gemini: backgroundCombinations.Blue,
        github: backgroundCombinations.Black,
        gmail: backgroundCombinations.Red,
        godaddy: backgroundCombinations.Teal,
        godot: backgroundCombinations.Blue,
        "godot engine": backgroundCombinations.Blue,
        google: backgroundCombinations.Teal,
        grubhub: backgroundCombinations.Rausch,
        harvard: backgroundCombinations.DarkRed,
        "harvard university": backgroundCombinations.DarkRed,
        hbo: backgroundCombinations.Black,
        "hbo max": backgroundCombinations.Purple,
        hcltech: backgroundCombinations.Blue,
        "hdfc bank": backgroundCombinations.Red,
        huawei: backgroundCombinations.Red,
        hubspot: backgroundCombinations.DarkOrange,
        hsbc: backgroundCombinations.Red,
        hulu: backgroundCombinations.Green,
        "icici bank": backgroundCombinations.Orange,
        ikea: backgroundCombinations.Yellow,
        instagram: backgroundCombinations.Pink,
        intel: backgroundCombinations.Blue,
        investopedia: backgroundCombinations.Blue,
        "johnson and johnson": backgroundCombinations.Red,
        "kth":backgroundCombinations.Blue,
        "khan academy": backgroundCombinations.Green,
        kickstarter: backgroundCombinations.Green,
        kpmg: backgroundCombinations.Blue,
        kraken: backgroundCombinations.Purple,
        lego: backgroundCombinations.Red,
        "lego house": backgroundCombinations.Red,
        linkedin: backgroundCombinations.Blue,
        lyft: backgroundCombinations.Pink,
        lufthansa: backgroundCombinations.Gold,
        marvel: backgroundCombinations.Red,
        mailchimp: backgroundCombinations.Yellow,
        marriott: backgroundCombinations.Teal,
        "marriott bonvoy": backgroundCombinations.Teal,
        marketwatch: backgroundCombinations.Green,
        mastercard: backgroundCombinations.Orange,
        medium: backgroundCombinations.Green,
        mecabricks: backgroundCombinations.Black,
        meta: backgroundCombinations.Blue,
        microsoft: backgroundCombinations.Teal,
        monday: backgroundCombinations.Purple,
        morningstar: backgroundCombinations.Red,
        "morgan stanley": backgroundCombinations.Blue,
        netflix: backgroundCombinations.Red,
        netgear: backgroundCombinations.Blue,
        "the new york times": backgroundCombinations.Black,
        nike: backgroundCombinations.Blue,
        notion: backgroundCombinations.Black,
        nvidia: backgroundCombinations.Green,
        openbank: backgroundCombinations.Purple,
        oracle: backgroundCombinations.Red,
        outlook: backgroundCombinations.Blue,
        panasonic: backgroundCombinations.Blue,
        paypal: backgroundCombinations.Blue,
        "pedro del hierro": backgroundCombinations.Black,
        pfizer: backgroundCombinations.Blue,
        pinterest: backgroundCombinations.Red,
        pocket: backgroundCombinations.Rausch,
        postmates: backgroundCombinations.Black,
        "prime video": backgroundCombinations.Blue,
        printables: backgroundCombinations.Orange,
        protonmail: backgroundCombinations.Purple,
        "proton mail": backgroundCombinations.Purple,
        quora: backgroundCombinations.DarkRed,
        reddit: backgroundCombinations.NeonOrange,
        reuters: backgroundCombinations.DarkOrange,
        revolut: backgroundCombinations.Black,
        robinhood: backgroundCombinations.Purple,
        rolex: backgroundCombinations.DarkGreen,
        safeway: backgroundCombinations.Red,
        samsung: backgroundCombinations.Blue,
        santander: backgroundCombinations.Red,
        sdu: backgroundCombinations.Black,
        shell: backgroundCombinations.Gold,
        shopify: backgroundCombinations.Green,
        siemens: backgroundCombinations.Teal,
        skype: backgroundCombinations.Blue,
        slack: backgroundCombinations.Purple,
        snapchat: backgroundCombinations.Lime,
        sofi: backgroundCombinations.Teal,
        sony: backgroundCombinations.Blue,
        sothebys: backgroundCombinations.Blue,
        spacex: backgroundCombinations.Black,
        spotify: backgroundCombinations.Green,
        square: backgroundCombinations.Black,
        starbucks: backgroundCombinations.DarkGreen,
        stripe: backgroundCombinations.Purple,
        substack: backgroundCombinations.NeonOrange,
        tata: backgroundCombinations.Purple,
        "tata consultancies": backgroundCombinations.Purple,
        "tata consultancy": backgroundCombinations.Purple,
        "tata consultancy services": backgroundCombinations.Purple,
        target: backgroundCombinations.Red,
        "td ameritrade": backgroundCombinations.DarkGreen,
        tencent: backgroundCombinations.Blue,
        tesla: backgroundCombinations.Red,
        "the guardian": backgroundCombinations.Blue,
        "the north face": backgroundCombinations.Blue,
        "the wall street journal": backgroundCombinations.Black,
        "the washington post": backgroundCombinations.Black,
        tiktok: backgroundCombinations.Blue,
        tinkercad: backgroundCombinations.Blue,
        todoist: backgroundCombinations.DarkRed,
        toyota: backgroundCombinations.Red,
        trello: backgroundCombinations.Blue,
        tumblr: backgroundCombinations.Purple,
        twitch: backgroundCombinations.Purple,
        twilio: backgroundCombinations.Rausch,
        twitter: backgroundCombinations.Blue,
        uber: backgroundCombinations.Black,
        "uber eats": backgroundCombinations.Green,
        ultimaker: backgroundCombinations.Blue,
        "ultimaker cura": backgroundCombinations.Blue,
        "unreal engine": backgroundCombinations.Black,
        ups: backgroundCombinations.Gold,
        uptimerobot: backgroundCombinations.Green,
        vanguard: backgroundCombinations.DarkRed,
        venmo: backgroundCombinations.Blue,
        verizon: backgroundCombinations.Red,
        vimeo: backgroundCombinations.Blue,
        visa: backgroundCombinations.Blue,
        "wall street journal": backgroundCombinations.Black,
        walmart: backgroundCombinations.Blue,
        "washington post": backgroundCombinations.Black,
        wechat: backgroundCombinations.Green,
        wework: backgroundCombinations.Black,
        whatsapp: backgroundCombinations.Green,
        wikipedia: backgroundCombinations.Black,
        wise: backgroundCombinations.Green,
        wordpress: backgroundCombinations.Blue,
        x: backgroundCombinations.Black,
        yahoo: backgroundCombinations.Purple,
        yelp: backgroundCombinations.Rausch,
        "yelmo cine": backgroundCombinations.DarkRed,
        "yelmo cines": backgroundCombinations.DarkRed,
        youtube: backgroundCombinations.Red,
        "youtube kids": backgroundCombinations.Red,
        zara: backgroundCombinations.Teak,
        zendesk: backgroundCombinations.DarkGreen,
        zoho: backgroundCombinations.Blue,
        zoom: backgroundCombinations.Blue,
        zoominfo: backgroundCombinations.Rausch,
        zomato: backgroundCombinations.DarkRed
    };
